# Current Alaskan sablefish stock assessment model {#modeldescription}
The latest published stock assessment [@goethel2021assessment] is a single area model (Chapter \@ref(modeldescription)). This chapter intends to extend this model by allowing it to be spatially disaggregated.

disaggregated integrated age-structured model. Let \(\boldsymbol{N_{y,s}}\) denote a vector of ages in year \(y\) for sex \(s\) (the partition) i.e., \(\boldsymbol{N_{y,s}} = (N_{1,y,s}, N_{2,y,s}, \dots, N_{a_+,y,s})^T\). The general process model is sequential and follows the general Equation \@ref(eq:processmodel),

\begin{equation} 
  \boldsymbol{N_{y,s}} = 
  \begin{cases}
  g\left(\boldsymbol{\theta}\right), & y = 1959 \text{ Initial model year}\\
  f\left(\boldsymbol{N_{y-1,s}}|\boldsymbol{\theta}\right), & y > 1959 \\
  \end{cases}
  (\#eq:processmodel)
\end{equation} 
where, \(g(.)\) is the function describing initial conditions for the partition and \(f(.)\) is the function that applies populations dyanmics each year i.e., birth, death, growth and migration. See Section \@ref(symbols) \& \@ref(modelequations) for a detailed description of \(g(.)\) and \(f(.)\) and \(\boldsymbol{\theta}\) is the set of estimable (not all are estimated) parameters.


Maximum Likelihood Estimates (MLE) for estimated parameters \(\widehat{\boldsymbol{\theta}}_{MLE}\) are evaluated,
\begin{equation}
	\widehat{\boldsymbol{\theta}}_{MLE} = \underset{\boldsymbol{\theta}}{\arg\max} \left( L\left(\boldsymbol{\theta} | \boldsymbol{y^{obs}}\right) \right)
	  (\#eq:observationmodel)
\end{equation}
where, \(\boldsymbol{y^{obs}}\) is a set of observations and \(L\left( . \right)\) is an objective function that is made up of priors/penalties and log-likelihood. See Section \@ref(observationsection)


## Process equations {#modelequations}

### Initialisation \left(\(g\left(.\right)\)\right) {-}
\begin{align*}
N_{a,1,s} = 
\begin{cases}
R_1, & a = a_1\\
\exp\bigg( \mu_r + \tau_{a_1 - a + 1}\bigg) \exp-\bigg( a - a_1\bigg) \bigg( M + F_{hist} * \mu_{LL} * S^{LL}_{a,1}\bigg), & a_0 < a < a_+\\
\exp( \mu_r) \exp-( a - 1) ( M + F_{hist} * \mu_{LL} * S^{LL}_{a - 1,1})(1 - \exp( M + F_{hist} * \mu_{LL} * S^{LL}_{a - 1,1}))^{-1}, &  a = a_+
\end{cases}
\end{align*}

### Population dynamics \left(\(f\left(.\right)\)\right) {-}
The assessment assumes a closed population that is only effected by mortality (natural and fishing), recruitment and growth. Mortality is applied assuming 

\[
Z_{a,y,s} = M + \sum_g F^g_{y} S^g_{a,y,s}
\]
where, \(S^g_{a,y,s}\) is the fishery selectivity and \(F^g_{y}\) is the annual estimated fishing mortality. The annual cycle follows,


\begin{align*}
N_{a,y,s} = 
\begin{cases}
p^s_{y} R_y, & a = a_1\\
N_{a - 1,y - 1,s} \times 
\exp\bigg( -Z_{a - 1,y - 1,s} \bigg), & a_0 < a < a_+\\
\exp\bigg( -Z_{a - 1,y - 1,s} \bigg) + \exp\bigg( -Z_{a,y - 1,s} \bigg), &  a = a_+
\end{cases}
\end{align*}
where,
\[
R_y = \exp\{\mu_r + \tau_y + 0.5\sigma_R^2\}
\]


### Determining selectivities for fisheries and surveys {-}
The ADMB model has a hard coded number of selectivities. Some of them relate to changes in the fishery and so represent time-varying blocks. We want to spell these out and simplify for the TMB model. There are nine selectivities labelled `fish1`, `fish2`, `fish3`, `fish4`, `fish5`, `srv1`, `srv2` and `srv10`.


+----------------------------+-----------------------------------------------------------------------------+
| label                      | Selectivity description                            
+============================+=============================================================================+
| `fish1`                    | Longline selectivity from 1960-1994
+----------------------------+-----------------------------------------------------------------------------+
| `fish2`                    | Not sure if this is used, maybe this is used for `srv6`?
+----------------------------+-----------------------------------------------------------------------------+
| `fish3`                    | Trawl selectivity from 1960 - \(T\)
+----------------------------+-----------------------------------------------------------------------------+
| `fish4`                    | Longline selectivity from 1995 -\( \ IFQ_y\) (\(IFQ_y\) can = \(T\)
+----------------------------+-----------------------------------------------------------------------------+
| `fish5`                    | Longline selectivity from \(IFQ_y \ - \ T\) if there is post IFQ block
+----------------------------+-----------------------------------------------------------------------------+
| `srv1`                     | Domestic Longline survey selectivity
+----------------------------+-----------------------------------------------------------------------------+
| `srv2`                     | Japanese Longline survey selectivity
+----------------------------+-----------------------------------------------------------------------------+


## Observation equations {#observationsection}
Three are three observational types in the current Sablefish stock assessment
- Relative abundance indices
- Age composition (aggregated over sex)
- Length composition (disaggregated by sex)

These three observation types come from both fishery dependent i.e., observer programs and CPUE and fishery independent i.e., research surveys.


### Catch at age {-}
Fishery dependent catch at age observations for gear type \(g\) denoted by \(\boldsymbol{C^g}_{a,y,s}\) are calculated as follows

\begin{equation} 
  \boldsymbol{C^g}_{a,y,s} = \frac{F^g_{a,y,s}}{Z_{a,y,s}}   N_{a,y,s} \left(1 - S_{a,y,s} \right)
  (\#eq:catchatage)
\end{equation} 
Currently all age observations are sex aggregated which means the model expected values before applying ageing error is
\[
  \boldsymbol{C^g}_{a,y} = 0.5 \sum_s \frac{\boldsymbol{C^g}_{a,y,s}}{\sum_a\boldsymbol{C^g}_{a,y,s}}
\]
why the 0.5? should be omitted going forward. Ageing error is then incorporated and the values are normalized so that they are proportions, before being passed to the multinomial log-likelihood function.



Survey age composition is similar but instead of being a function of \(F\) it is calculated at the beginning of the year. For survey \(k\) the numbers at age are denoted by \(\boldsymbol{C^k}_{a,y}\) and calculated following
\begin{equation} 
  \boldsymbol{C^k}_{a,y} = p^s N_{a,y,s} S^k_{y,a,s}
  (\#eq:surveyage)
\end{equation} 

I am not sure exactly what the timing of these surveys are, but do we need to account for som mid-year mortality? or changes in timing of the survey? if so we could easily replace 
\[
N_{a,y,s}
\]
with
\[
N_{a,y,s} \exp\{-p^k_y Z_{a,y,s}\} 
\]
where,\(p^k_y\) is the proportion of mortality that we want to account for in year \(y\) for survey \(k\).

The survey numbers at age are then adjusted for ageing error and normalised so they sum to one for each year.


### Relative abundance indices {-}
\begin{equation} 
  \widehat{I}^g_{y} = \sum_s\sum_a p^s N_{a,y,s} \exp \{-0.5 Z_{a,y,s}\} S^g_{y,a,s} \bar{w}_{a,y,s}
  (\#eq:relativeindex)
\end{equation} 
where, \(\bar{w}_{a,y,s}\) is mean weight at age, this can be omitted if the observation is in numbers i.e., abundance instead of biomass and \(p^s\) is the proportion for each sex. This is currently a user input, but should be dealt within the model either as having different sex selectivities or through the sex ratio of recruitment.

A list of slight improvements

- change how sex ratio is handled
- fishery dependent abundance indices i.e., CPUE change \(N_{a,y,s} \exp \{-0.5 Z_{a,y,s}\}\) with \(\boldsymbol{C^g}_{a,y,s}\) which is calculated in the catch at age observations.

### Catch at length {-}

For each year that has a length frequency observation, numbers at length denoted by \(\boldsymbol{C^l}_{y,s} = (C^l_{1,y,s}, \dots, C^l_{n_l,y,s})^T\) (dimension of \(\boldsymbol{C^l}_{y,s}\) is \(n_l \ \times \ 1\)) were calculated for each sex. This involved multiplying the catch at age (see above for how it is calculated) through an age-length transition matrix denoted by \(\boldsymbol{A}^l_{y,s}\) (dimensions of \(\boldsymbol{A}^l_{y,s}\) are \(n_a \ \times \ n_l\) and its rows must sum to 1). The calculation follows Equation \@ref(eq:agelengthtransition),

\begin{equation} 
  \boldsymbol{C^l}_{y,s} =  \left(\boldsymbol{A}^l_{y,s} \right)^T \ \times \ \boldsymbol{C_{y,s}}
  (\#eq:agelengthtransition)
\end{equation} 
where, \(\boldsymbol{C_{y,s}}\) is a column vector of numbers at age (dimension \(n_a \ \times \ 1\)) at the beginning of year \(y\) for sex \(s\).




### Observations for fisheries and surveys {-}

+----------------------------+-----------------------------------------------------------------------------+
| label                      | Relative Abundance description                            
+============================+=============================================================================+
| `srv1`                     | Biomass domestic longline survey uses both `srv1_sel` and `srv10_sel`
+----------------------------+-----------------------------------------------------------------------------+
| `srv3`                     | Abundance domestic longline survey uses both `srv1_sel` and `srv10_sel`
+----------------------------+-----------------------------------------------------------------------------+
| `srv2`                     | Biomass survey uses both `srv2_sel` and `srv9_sel`
+----------------------------+-----------------------------------------------------------------------------+
| `srv4`                     | Abundance survey uses both `srv2_sel` and `srv9_sel`
+----------------------------+-----------------------------------------------------------------------------+
| `srv5`                     | Longline fishery CPUE `fish1_sel`, `fish4_sel`, `fish5_sel`
+----------------------------+-----------------------------------------------------------------------------+
| `srv6`                     | Japanese LL fishery CPUE
+----------------------------+-----------------------------------------------------------------------------+
| `srv7`                     | NMFS bottom trawl survey (currently GOA only; fit in model)
+----------------------------+-----------------------------------------------------------------------------+



+----------------------------+-----------------------------------------------------------------------------+
| label                      | Composition description                            
+============================+=============================================================================+
| `ac_fish1`                 | Longline Fishery Age Comp (sex aggregated)
+----------------------------+-----------------------------------------------------------------------------+
| `sc_fish1`                 | Longline Fishery LF (sex dis-aggregrated)
+----------------------------+-----------------------------------------------------------------------------+
| `sc_fish3`                 | Trawl Fishery LF (sex disaggregrated)
+----------------------------+-----------------------------------------------------------------------------+
| `sc_fish2`                 | LF for japaneses Longline fishery (sex aggregrated) (basically a survey now)
+----------------------------+-----------------------------------------------------------------------------+
| `sc_fish4`                 | LF for japaneses Longline fishery (sex aggregrated) (basically a survey now)
+----------------------------+-----------------------------------------------------------------------------+
| `fish_size`                | LF From japaneses trawl survey? (sex aggregrated)
+----------------------------+-----------------------------------------------------------------------------+
| `ac_srv1`                  | Domestic Longline Survey AF (sex aggregated)
+----------------------------+-----------------------------------------------------------------------------+
| `sc_srv1`                  | Domestic Longline Survey LF (sex disaggregrated)
+----------------------------+-----------------------------------------------------------------------------+
| `ac_srv2`                  | Japanese Longline Survey AF (sex aggregated)
+----------------------------+-----------------------------------------------------------------------------+
| `sc_srv2`                  | Japanese Longline Survey LF (sex disaggregrated)
+----------------------------+-----------------------------------------------------------------------------+
| `ac_srv7`                  | NMFS bottom trawl survey AF (sex aggregated)
+----------------------------+-----------------------------------------------------------------------------+
| `sc_srv7`                  | NMFS bottom trawl survey LF (sex disaggregrated)
+----------------------------+-----------------------------------------------------------------------------+
## Symbol Notation {#symbols}
+----------------------------+-----------------------------------------------------------------------------+
| Symbol                     | Description                            
+============================+=============================================================================+
| \(y\)                      | Year, \(y = 1960, \dots, T\) 
+----------------------------+-----------------------------------------------------------------------------+
| \(T\)                      | Terminal year of the model
+----------------------------+-----------------------------------------------------------------------------+
| \(s\)                      | Sex index \(s \in \{1,2\}\)
+----------------------------+-----------------------------------------------------------------------------+
| \(r\)                      | Region index \(r \in \{1, \dots, n_r\}\)
+----------------------------+-----------------------------------------------------------------------------+
| \(n_r\)                    | number of modeled regions
+----------------------------+-----------------------------------------------------------------------------+
| \(a\)                      | Model age cohort, i.e., \(a = a_0, a_0 + 1, \dots\)
+----------------------------+-----------------------------------------------------------------------------+
| \(a_{1}\)                  | Recruitment age to the model = 2 
+----------------------------+-----------------------------------------------------------------------------+
| \(a_+\)                    | Plus-group age class (oldest age considered plus all older ages)
+----------------------------+-----------------------------------------------------------------------------+
| \(n_a\)                    | Number of age classes modeled \(a_+ \ - a_1\)
+----------------------------+-----------------------------------------------------------------------------+
| \(l\)                      | length class
+----------------------------+-----------------------------------------------------------------------------+
| \(n_l\)                    | Number of length classes
+----------------------------+-----------------------------------------------------------------------------+
| \(g\)                      | gear type index, i.e. longline survey, longline fishery, trawl fishery
+----------------------------+-----------------------------------------------------------------------------+
| \(x\)                      | log-likelihoos index
+----------------------------+-----------------------------------------------------------------------------+
| \(\bar{w}_{a,y, s}\)       | Average weight at age \(a\), year \(y\) and sex \(s\)
+----------------------------+-----------------------------------------------------------------------------+
| \(\phi_{a,y}\)             | Proportion of female mature by age and year
+----------------------------+-----------------------------------------------------------------------------+
| \(p^s_{y}\)                | Proportion of recruits for sex \(s\). Often assumed = 0.5
+----------------------------+-----------------------------------------------------------------------------+
| \(\ln \mu_{r}\)            | Average log-recruitment
+----------------------------+-----------------------------------------------------------------------------+
| \(\ln \mu_{f}\)            | Average log-fishing mortality
+----------------------------+-----------------------------------------------------------------------------+
| \(\phi_{y,g}\)             | annual fishing mortality deviation by gear (log space)
+----------------------------+-----------------------------------------------------------------------------+
| \(\tau_{y}\)               | annual recruitment deviation \(\sim LogNormal\left(0,\sigma_r\right)\)
+----------------------------+-----------------------------------------------------------------------------+
| \(\sigma_r\)               | Recruitment standard deviation
+----------------------------+-----------------------------------------------------------------------------+
| \(N_{a,y,s}\)              | Numbers of fish at age \(a\) in year \(y\) of sex \(s\)
+----------------------------+-----------------------------------------------------------------------------+
| \(M\)                      | Natural mortality
+----------------------------+-----------------------------------------------------------------------------+
| \(F^g_{a,y}\)              | Fishing mortality for year \(y\), age \(a\) and gear \(g\)
+----------------------------+-----------------------------------------------------------------------------+
| \(F_{hist}\)               | Historical proportion of Fishing mortality 
+----------------------------+-----------------------------------------------------------------------------+
| \(Z_{a,y}\)                | Total mortality for year \(y\), age \(a\) \(=\sum\limits_g F^g_{a,y} + M\)
+----------------------------+-----------------------------------------------------------------------------+
| \(R_{y}\)                  | Annual recruitment
+----------------------------+-----------------------------------------------------------------------------+
| \(B_{y}\)                  | Spawning biomass in year \(y\)
+----------------------------+-----------------------------------------------------------------------------+
| \(S^g_{a,y,s}\)            | Selectivity at age \(a\) for gear type \(g\) and sex \(s\)
+----------------------------+-----------------------------------------------------------------------------+
| \(a_50\)                   | age at 50\% selection for ascending limb 
+----------------------------+-----------------------------------------------------------------------------+
| \(d_50\)                   | age at 50\% selection for descending limb 
+----------------------------+-----------------------------------------------------------------------------+
| \(\delta\)                 | slope/shape parameters for different logistic curves
+----------------------------+-----------------------------------------------------------------------------+
| \(\boldsymbol{A}\)         | ageing-error matrix dimensions \(n_a \ \times \ n_a\)
+----------------------------+-----------------------------------------------------------------------------+
| \(\boldsymbol{A}^l_s\)     | age to length conversion matrix by sex. dimensions  \(n_a \ \times \ n_l\)
+----------------------------+-----------------------------------------------------------------------------+
| \(q_g\)                    | abundance index catchability coeffecient by gear
+----------------------------+-----------------------------------------------------------------------------+
| \(\lambda_x\)              | Statistical weight (penalty) for component \(x\)
+----------------------------+-----------------------------------------------------------------------------+
| \(P^g_{l,y,s}\)            | Observed proportions at length for gear \(g\) in year \(y\) and sex \(s\)
+----------------------------+-----------------------------------------------------------------------------+
| \(P^g_{a,y,s}\)            | Observed proportions at age for gear \(g\) in year \(y\) and sex \(s\)
+----------------------------+-----------------------------------------------------------------------------+
| \(\psi^g_{y}\)             | assumed sample size for gear \(g\) in year \(y\) (for multinomial likelihood)
+----------------------------+-----------------------------------------------------------------------------+
| \(n_g\)                    | Number of years that age (or length) composition is available for gear \(g\)
+----------------------------+-----------------------------------------------------------------------------+


## Inference {-}
If random effects are considered the joint probability model follows,
	\begin{equation}
	Pr\left[ \boldsymbol{y^{obs}}, \boldsymbol{u}| \boldsymbol{\theta} \right]  = Pr\left[\boldsymbol{y^{obs}} |\boldsymbol{\theta^f}, \boldsymbol{u} \right] Pr\left[\boldsymbol{u} |\boldsymbol{\theta^h} \right] 
	\end{equation}

Inference is conducted by maximising the marginal likelihood noting \( L\left(\boldsymbol{\theta} | \boldsymbol{y^{obs}} \right) \propto Pr\left[ \boldsymbol{y^{obs}} | \boldsymbol{\theta} \right]\)
	\begin{equation}\label{eq:marginal_ll}
	L\left(\boldsymbol{\theta} | \boldsymbol{y^{obs}}\right) = \int \left(Pr\left[\boldsymbol{y^{obs}} |\boldsymbol{\theta^f}, \boldsymbol{\theta^g}, \boldsymbol{u} \right] Pr\left[\boldsymbol{u} |\boldsymbol{\theta^h} \right] \right) \boldsymbol{du}
	\end{equation}
In general this integral is not tractable, and so approximations are necessary. The software used here implement the Laplace approximation, which relies on Gaussian assumptions.

Maximum Likelihood Estimates (MLE) for fixed effect parameters \(\widehat{\boldsymbol{\theta}}_{MLE}\) are evaluated,
\begin{equation}
	\widehat{\boldsymbol{\theta}}_{MLE} = \underset{\boldsymbol{\theta}}{\arg\max} \left( L\left(\boldsymbol{\theta} | \boldsymbol{y^{obs}}\right) \right)
\end{equation}

and Empirical Bayes estimates are evaluated for \(\widehat{\boldsymbol{u}}\), which are used model diagnostics and other model quantities,
\begin{equation}
\widehat{\boldsymbol{u}} = \underset{\boldsymbol{u}}{\arg\max} \left( Pr\left[ \boldsymbol{y^{obs}}, \boldsymbol{u}| \widehat{\boldsymbol{\theta}}_{MLE} \right] \right)
\end{equation}


## TODO {-}
- Build a validate function to help catch users setting up parameters or data structures that will cause a crash once supplied to TMB.
- Self test
- change some parameter containers. In the ADMB model the often share parameters between male and females. Particularly for selectivity parameters. However TMB will not allow us to fix/map parameters across different arrays or vectors. This means we will want to join the male and female selectivity parameter objects into a single object so that we can share parameters between the sexes.
- Change array column casting from `vector<Type>(array.col(i))` to `array.col(i).vec()`
