# Exploring methods for sex ratios in age and length composition data {#sexratios}

One of the needed improvements is dealing with sex ratios in the compositional data. Currently it is difficult to see how there is any information on sex ratio in the Sablefish stock assessment given how the observations are structured (Chapter \@ref(modeldescription)) (Caveat is users can provide an observed sex ratio for observations etc which is similar to the approach in @ward2019assessing). I am aware of two approaches for supplying observations that in theory should provide information on sex ratio. The first was taken from Casal2 [@doonan2016casal2]. This treats sexed composition data for a year as a single proportion i.e., proportions across all ages and sexes sum to one for each year of observation. Catch at age (in numbers) for both sexes is denoted by \(\boldsymbol{C^k}_{a,y} = (\boldsymbol{C^k}_{a,y,1},\boldsymbol{C^k}_{a,y,2})\), where \(\boldsymbol{C^k}_{a,y,1}\) is the catch at age for males and \(\boldsymbol{C^k}_{a,y,2}\) is for females, and 

\[
\boldsymbol{P^k}_{a,y} = \frac{\boldsymbol{C^k}_{a,y}}{\sum_a \sum_s \boldsymbol{C^k}_{a,y,s}}
\]


The second approach is to provide a specific sex ratio observation over all ages or lengths as done in the New Zealand rock lobster stock assessment [@webber2021rapid]. 


\[
R^k_{y,s} = \frac{\sum_a \boldsymbol{C^k}_{a,y,s}}{\sum_a \sum_s \boldsymbol{C^k}_{a,y,s}}
\]


A simple simulation experiment was conducted to explore the benefits of each approach. There were two OM scenarios that we wanted to explore, the first was that the true population had a 50:50 sex ratio and the observations had skewed sex ratios due to the selectivity i.e., availability to the survey fishery. Second the selectivity was constant for both sexes but the sex ratio was skewed at recruitment.





## Other things to consider {-}


- LF observations with sexual dimorphism in growth. A possible reason LF's could be influencing assessment output is due to mis-specified growth ala 


